### PR TITLE
home page hero section modified

### PR DESCRIPTION
**Pull request by ashuvssut**
image

### CODE REVIEW

**Comment by ashuvssut** [comment]
@EnigmaVSSUT/admins please review

**Comment by partha2000** [comment]
@ashuvssut This looks nice but replace *some floating text might look nyc* to some nice catchphrase or merely to *Enigma The coding club*.

**Comment by ashuvssut** [comment]
@partha2000 I asked the same in the whatsapp group but nobody replied.😓

**Comment by ashuvssut** [comment]
done

**Pull request merged**
