### PR TITLE
home page and sign up page styling

### PR DESCRIPTION
**Pull request by ashuvssut**
## login page
image
image

## signup page

image
image

### CODE REVIEW

**Comment by partha2000** [comment]
@ashuvssut We will not use github, linkedin and facebook for login anymore. Secondly have you tested this on local.

**Comment by ashuvssut** [comment]
@partha2000 i was able to edit the css only by using/running the django server.
So, YES,  it is tested and it works all right.

I will comment out GH linkedin and FB Oauth provider button shortly

**Comment by ashuvssut** [comment]
requested changes added

image

**Comment by partha2000** [comment]
This is not required as of now. There is a small change in plan.

**Comment by ashuvssut** [comment]
So signin & signup page is not required😟😕?

**Comment by partha2000** [comment]
No not required as of now. It will be added in the new website.

**Pull request closed without merging**
